
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class PesanMakanan extends javax.swing.JFrame {

    /**
     * Creates new form PesanMakanan
     */

    String[] dataMakanan = {
    "Nasi Goreng - 15000", "Nasi Kuning - 12000", "Nasi Pecel - 10000", 
    "Nasi Tiwul - 8000", "Mie Goreng - 13000", "Mie Kuah - 13000", 
    "Mie Topping - 18000", "Mie Gacoan - 15000", "Mie Ayam - 12000", 
    "Mie Pangsit - 14000", "Ramen - 25000", "Seblak - 15000", 
    "Topokki - 20000", "Bakso Bulat - 15000", "Bakso Jumbo - 25000", 
    "Bakso Peler Kuda - 35000", "Oseng Brutu - 20000", "Oseng Kecubung - 25000", 
    "Bakso Kotak - 17000", "Ketupat - 5000"
};
    String[] dataMinuman = {
    "Air Putih - 3000", "Air Default - 2000", "Air Sungai - 500", 
    "Air Ketuban - 100000", "ASI - 50000", "Es Teh Manis - 5000", 
    "Es Teh Asin - 5000", "Es Teh Anget - 4000", "Kuah - 2000", 
    "Ameer - 35000", "Arak - 45000", "Bintang - 35000", 
    "Coca Cola - 8000", "Sprite - 8000", "Fanta - 8000", 
    "Kopi - 5000", "Americano - 15000", "Indonesiano - 12000", 
    "Es Jeruk - 7000", "Es Batu - 1000"
};
    String[] dataSnack = {
    "Surya - 30000", "Andalan - 25000", "Dua Dewi - 20000", 
    "Samsu - 28000", "Sampoerna - 32000", "Ciki - 5000", 
    "Puding - 7000", "Putu Ayu - 3000", "Suki - 15000", 
    "Taro - 6000", "Sabu - 150000", "Steroid - 200000", 
    "Peptide - 180000", "Sawit - 10000", "Basreng - 10000", 
    "Opak - 5000", "Canggei - 5000", "Ampyang - 8000", 
    "Lemet - 4000", "Cethe - 2000"
            
};
    public PesanMakanan() {
        initComponents();
        kategori.addItem("Makanan");
        kategori.addItem("Minuman");
        kategori.addItem("Snack");

        buttonGroup1.add(bungkus);
        buttonGroup1.add(makansini);
        bungkus.setSelected(true);
        
        buttonGroup2.add(cash);
        buttonGroup2.add(qris);
        buttonGroup2.add(utang);
        cash.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        meja = new javax.swing.JTextField();
        pesan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JList<>();
        bungkus = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        makansini = new javax.swing.JRadioButton();
        quantity = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        request = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        qris = new javax.swing.JRadioButton();
        utang = new javax.swing.JRadioButton();
        addcart = new javax.swing.JButton();
        all = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cartArea = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No :");

        meja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejaActionPerformed(evt);
            }
        });

        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Category :");

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });

        proses.setBackground(new java.awt.Color(102, 102, 255));
        proses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proses.setForeground(new java.awt.Color(255, 255, 255));
        proses.setText("PROCESS");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(menu);

        bungkus.setText("Bungkus");
        bungkus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bungkusActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Order Type :");

        makansini.setText("Makan Sini");
        makansini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makansiniActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Quantity :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Request :");

        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setFont(new java.awt.Font("Exotc350 Bd BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PANGGONAN MBADHOK");

        jLabel9.setFont(new java.awt.Font("Exotc350 DmBd BT", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Waroenk WareG");

        jLabel10.setFont(new java.awt.Font("Humanst521 BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Silahkan Pesan Sepuasnya Sampai Anda Wareg");

        jLayeredPane3.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane3.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(241, 241, 241))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(289, 289, 289))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Payment :");

        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        qris.setText("Qris");

        utang.setText("Utang");
        utang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utangActionPerformed(evt);
            }
        });

        addcart.setBackground(new java.awt.Color(153, 153, 153));
        addcart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addcart.setForeground(new java.awt.Color(255, 255, 255));
        addcart.setText("Add Cart");
        addcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcartActionPerformed(evt);
            }
        });

        all.setBackground(new java.awt.Color(153, 153, 153));
        all.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        all.setForeground(new java.awt.Color(255, 255, 255));
        all.setText("See All");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Voucher :");

        jLayeredPane1.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Menu :");

        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Exotc350 DmBd BT", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Waroenk WareG");

        jLabel15.setFont(new java.awt.Font("Humanst521 BT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Silahkan Pesan Sepuasnya Sampai Anda Wareg");

        jLabel13.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pesan Lagi Jika anda Kurang WareG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(174, 174, 174))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane2.setForeground(new java.awt.Color(0, 0, 102));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Cart :");

        jLayeredPane2.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLayeredPane2)
                        .addGap(18, 18, 18)
                        .addComponent(cartArea, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(33, 33, 33)
                                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(31, 31, 31)
                                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(meja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(makansini)
                                            .addComponent(bungkus))))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cash)
                                        .addGap(30, 30, 30)
                                        .addComponent(qris)
                                        .addGap(18, 18, 18)
                                        .addComponent(utang))
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(all))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(addcart)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(proses, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(request, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(request, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bungkus)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(makansini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cash)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qris)
                            .addComponent(utang))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cartArea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(proses, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addcart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mejaActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesanActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        String Pilihan=kategori.getSelectedItem().toString();
        String[]data = null;
        if (Pilihan.equals("Makanan")) {
    data = new String[]{
        "Nasi Goreng - 15000", 
        "Nasi Kuning - 12000",
        "Nasi Pecel - 10000",
        "Nasi Tiwul - 8000",
        "Mie Goreng - 13000",
        "Mie Kuah - 13000",
        "Mie Topping - 18000",
        "Mie Gacoan - 15000",
        "Mie Ayam - 12000",
        "Mie Pangsit - 14000",
        "Ramen - 25000",
        "Seblak - 15000",
        "Topokki - 20000",
        "Bakso Bulat - 15000",
        "Bakso Jumbo - 25000",
        "Bakso Peler Kuda - 35000",
        "Oseng Brutu - 20000",
        "Oseng Kecubung - 25000",
        "Bakso Kotak - 17000",
        "Ketupat - 5000"
    };
} else if (Pilihan.equals("Minuman")) {
    data = new String[]{
        "Air Putih - 3000", 
        "Air Default - 2000", 
        "Air Sungai - 500",
        "Air Ketuban - 100000",
        "ASI - 50000",
        "Es Teh Manis - 5000",
        "Es Teh Asin - 5000",
        "Es Teh Anget - 4000",
        "Kuah - 2000",
        "Ameer - 35000",
        "Arak - 45000",
        "Bintang - 35000",
        "Coca Cola - 8000",
        "Sprite - 8000",
        "Fanta - 8000",
        "Kopi - 5000",
        "Americano - 15000",
        "Indonesiano - 12000",
        "Es Jeruk - 7000",
        "Es Batu - 1000"
    };
} else {
    data = new String[]{
        "Surya - 30000", 
        "Andalan - 25000", 
        "Dua Dewi - 20000",
        "Samsu - 28000",
        "Sampoerna - 32000",
        "Ciki - 5000",
        "Puding - 7000",
        "Putu Ayu - 3000",
        "Suki - 15000",
        "Taro - 6000",
        "Sabu - 150000",
        "Steroid - 200000",
        "Peptide - 180000",
        "Sawit - 10000",
        "Basreng - 10000",
        "Opak - 5000",
        "Canggei - 5000",
        "Ampyang - 8000",
        "Lemet - 4000",
        "Cethe - 2000"
    };
        }
        menu.setListData(data);
    }//GEN-LAST:event_kategoriActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        
    String noMeja = meja.getText();
    String namaPemesan = pesan.getText();
    String req = request.getText();
    
    
    String listMenu = menu.getSelectedValue(); 
    String[] parts = listMenu.split("-"); 
    int hargaSatuan = Integer.parseInt(parts[1].trim()); 
    
    
    int qty = Integer.parseInt(quantity.getValue().toString()); 
    int totalHarga = hargaSatuan * qty; 
    if (qty <= 0) {
        JOptionPane.showMessageDialog(this, "Quantity minimal 1 ya!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    
    String takeAway = "";
    if (bungkus.isSelected()) { takeAway = "Bungkus"; }
    else if (makansini.isSelected()) { takeAway = "Makan Sini"; }
    else { takeAway = "Belum Dipilih"; }

    String bayar = "";
    if (cash.isSelected()) { bayar = "Cash"; }
    else if (qris.isSelected()) { bayar = "Qris"; }
    else { bayar = "Utang"; }
     


String inputVoucher = pass.getText().trim(); 
int diskon = 0;
String infoVoucher = "-";

if (!inputVoucher.isEmpty()) { 
    if (inputVoucher.equals("232323")) {
        diskon = (totalHarga * 10) / 100; 
        totalHarga = totalHarga - diskon; 
        infoVoucher = "Sukses! Diskon 10%";
        JOptionPane.showMessageDialog(this, "Kode Voucher '" + inputVoucher + "' Berhasil!", "Voucher Berhasil Dipakai", JOptionPane.INFORMATION_MESSAGE);
    } else {
        infoVoucher = "INVALID";
        
        JOptionPane.showMessageDialog(this, "Kode Voucher '" + inputVoucher + "' tidak valid!", "Voucher Error", JOptionPane.WARNING_MESSAGE);
    }
}


    
String gabung = "--------------------------------------------"+
                "\n~ No Meja: " + noMeja +
                "\n~ Name: " + namaPemesan +
                "\n~ Order Type: " + takeAway +
                "\n--------------------------------------------" +
                "\n~ Menu: " + listMenu +
                "\n~ Quantity: " + qty +
                "\n~ Request: " + (req.isEmpty() ? "-" : req) +
                "\n--------------------------------------------" +
                "\n~ Voucher: " + infoVoucher + 
                "\n~ TOTAL BAYAR: Rp " + totalHarga +
                "\n~ Payment: " + bayar+
                "\n--------------------------------------------";


JOptionPane.showMessageDialog(this,"RINCIAN PESANAN\n\n"+ gabung + "\n\nPESANAN DI PROSES!");
    }//GEN-LAST:event_prosesActionPerformed

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestActionPerformed

    private void bungkusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bungkusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bungkusActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashActionPerformed

    private void utangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utangActionPerformed

    private void addcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcartActionPerformed
        
    if (menu.getSelectedValue() == null) {
        JOptionPane.showMessageDialog(this, "Silahkan pilih menu yang mau dimasukkan ke keranjang!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; 
    }

    
    int qty = Integer.parseInt(quantity.getValue().toString()); 
    if (qty <= 0) {
        JOptionPane.showMessageDialog(this, "Quantity minimal 1 ya!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    String listMenu = menu.getSelectedValue(); 
    int hargaSatuan = 0;
    String namaMenu = "";

    try {
        String[] parts = listMenu.split("-"); 
        namaMenu = parts[0].trim(); 
        hargaSatuan = Integer.parseInt(parts[1].trim()); 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Format menu salah!");
        return;
    }

    
    int subtotal = hargaSatuan * qty; 

    
    String takeAway = "";
    if (bungkus.isSelected()) { takeAway = " (Bungkus)"; }
    else if (makansini.isSelected()) { takeAway = " (Makan Sini)"; }

    
    String itemPesanan = "- " + namaMenu + takeAway + "\t x" + qty + " \t = Rp " + subtotal + "\n";

    
    cartArea.setText(itemPesanan); 

    
    quantity.setValue(0);
        
    }//GEN-LAST:event_addcartActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed


    
StringBuilder makananHtml = new StringBuilder("<b>[ MAKANAN ]</b><br>");
for (String item : dataMakanan) {
    makananHtml.append("- ").append(item).append("<br>");
}

StringBuilder minumanHtml = new StringBuilder("<b>[ MINUMAN ]</b><br>");
for (String item : dataMinuman) {
    minumanHtml.append("- ").append(item).append("<br>");
}

StringBuilder snackHtml = new StringBuilder("<b>[ SNACK ]</b><br>");
for (String item : dataSnack) {
    snackHtml.append("- ").append(item).append("<br>");
}


String layoutFinal = "<html>" +
    "<div style='text-align: center; font-size: 14px;'><b>--- MENU WAROENK WAREG ---</b></div><br>" +
    "<table border='0' cellpadding='10'>" + 
    "<tr>" +
        "<td valign='top'>" + makananHtml.toString() + "</td>" + 
        "<td valign='top' style='border-left: 1px solid black;'>" + minumanHtml.toString() + "</td>" + 
        "<td valign='top' style='border-left: 1px solid black;'>" + snackHtml.toString() + "</td>" + 
    "</tr>" +
    "</table>" +
    "</html>";


JOptionPane.showMessageDialog(this, layoutFinal);
    }//GEN-LAST:event_allActionPerformed

    private void makansiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makansiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makansiniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcart;
    private javax.swing.JButton all;
    private javax.swing.JRadioButton bungkus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cartArea;
    private javax.swing.JRadioButton cash;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JRadioButton makansini;
    private javax.swing.JTextField meja;
    private javax.swing.JList<String> menu;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField pesan;
    private javax.swing.JButton proses;
    private javax.swing.JRadioButton qris;
    private javax.swing.JSpinner quantity;
    private javax.swing.JTextField request;
    private javax.swing.JRadioButton utang;
    // End of variables declaration//GEN-END:variables
}
